<?php
declare(strict_types=1);

namespace App\Core\Route;

use App\Core\Controller\ControllerTemplate;

class RouteGroup
{
    /** @var list<class-string<RouteTemplate>> */
    private array $routes = [];

    public function __construct(array $routes)
    {
        $this->routes = $routes;
    }

    private static function create_path_from_name(string $name): string
    {
        $value = preg_replace('/([a-z])([A-Z])/', '$1-$2', $name);

        $value = preg_replace('/([A-Z]+)([A-Z][a-z])/', '$1-$2', $value);
        $value = strtolower($value ?? '');
        $value = str_replace(' ', '-', $value);
        return $value;
    }

    /** @return array<string, array<int|class-string<ControllerTemplate>, class-string<ControllerTemplate>|'HIDE'>> */
    private function get_controler_classes(): array
    {
        /** @var array<string, array<int|class-string<ControllerTemplate>, class-string<ControllerTemplate>|'HIDE'>> */
        $all_routes = [];
        foreach ($this->routes as $route) {
            $r                             = new $route();
            $all_routes[$r->feature_group] = $r->features;
        }
        return $all_routes;
    }

    final public function create_routes(): array
    {
        $groups = [];

        foreach ($this->get_controler_classes() as $group => $features) {
            $group_path = self::create_path_from_name($group);
            // Role yang boleh baca/tulis grup ini adalah data (tabel
            // auth.akses_fitur), bukan kode; lihat App\Core\Auth\AccessMatrix.
            $filter_read  = ['filter' => "checkpermission:{$group_path},read"];
            $filter_write = ['filter' => "checkpermission:{$group_path},write"];

            foreach ($features as $f => $show) {
                if ($show !== 'HIDE') {
                    $f = $show;
                }
                $title        = new $f()->title;
                $feature_path = self::create_path_from_name($title);
                ;
                $path = "{$group_path}/{$feature_path}/";

                $route_group = [
                    'prefix'  => $path,
                    'options' => ['filter' => 'auth'],
                    'routes'  => [],
                ];
                // Elemen ke-4: READ hanya melihat data, WRITE mengubah data;
                // masing-masing dijaga filter checkpermission,<grup>,read|write.
                $paths = [
                    ['get',    'data',                  'index',          'READ'],
                    ['get',    'audit',                 'audit',          'READ'],
                    ['get',    'tambah',                'create_page',    'WRITE'],
                    ['post',   'submittambah',          'create',         'WRITE'],
                    ['get',    'edit/(:segment)',       'update_page/$1', 'WRITE'],
                    ['post',   'submitedit/(:segment)', 'update/$1',      'WRITE'],
                    ['delete', 'hapus/(:segment)',      'delete/$1',      'WRITE'],
                    ['get',    'cetak/(:segment)',      'print/$1',       'READ'],
                    ['get',    'modal/list',            'list',           'READ'],
                    ['post',   'sampel/(:segment)',     'sampel/$1',      'WRITE'],
                    ['post',   'bayar/(:segment)',      'bayar/$1',       'WRITE'],
                    ['post',   'upload/(:num)',         'upload/$1',      'WRITE'],
                    ['post',   'hapus-foto/(:num)',     'hapusFoto/$1',   'WRITE'],
                    ['get',    'tampil/(:num)',         'tampil/$1',      'READ'],
                    ['get',    '(:segment)',            'detail/$1',      'READ'],
                ];

                foreach ($paths as $p) {
                    [$method, $uri, $action, $access] = $p;
                    $route_group['routes'][] = [
                        'method'  => $method,
                        'uri'     => $uri,
                        'action'  => $action,
                        'class'   => $f,
                        'options' => $access === 'WRITE' ? $filter_write : $filter_read,
                    ];
                }
                $groups[] = $route_group;
            }
        }

        return $groups;
    }

    final public function generate_php(): string
    {
        $groups = $this->create_routes();
        $php    = <<<'PHP'
            <?php

            /**
             * --------------------------------------------------------------------
             * AUTO-GENERATED FILE
             * --------------------------------------------------------------------
             * This file was generated by `php spark omnia:route`.
             * Do not edit this file manually.
             */

            use CodeIgniter\Router\RouteCollection;
            /**
             * @var RouteCollection $routes
             */

            PHP;

        foreach ($groups as $group) {
            $php .= sprintf(
                "\n\$routes->group(%s, ['filter' => '%s'], static function (RouteCollection \$routes) {\n",
                var_export($group['prefix'], true),
                $group['options']['filter'],
            );

            foreach ($group['routes'] as $route) {
                $php .= sprintf(
                    "    \$routes->%s(%s, [\\%s::class, %s], ['filter' => '%s']);\n",
                    $route['method'],
                    var_export($route['uri'], true),
                    $route['class'],
                    var_export($route['action'], true),
                    $route['options']['filter'],
                );
            }
            $php .= "});\n";
        }

        return $php;
    }

    private function get_icons(): array
    {
        /** @var array<string, string> */
        $all_icons = [];
        foreach ($this->routes as $route) {
            $r                            = new $route();
            $all_icons[$r->feature_group] = $r->icon;
        }
        return $all_icons;
    }

    final public function create_sidebar()
    {
        $all_routes = $this->get_controler_classes();
        $all_icons  = $this->get_icons();
        $all_header = [];

        foreach ($all_routes as $group => $features) {
            $group_path = self::create_path_from_name($group);
            $icon       = $all_icons[$group];

            if (count($features) === 1) {
                $title        = new $features[0]()->title;
                $feature_path = self::create_path_from_name($title);
                $header       = [
                    $group,
                    '/' . $group_path . '/' . $feature_path . '/data',
                    $icon,
                    '',
                    $group_path,
                    [],
                ];
            } else {
                $header = [$group, '', $icon, '/' . $group_path, $group_path];
                foreach ($features as $feature => $show) {
                    if ($show !== 'HIDE') {
                        $feature = $show;
                    } else {
                        continue;
                    }

                    $f            = new $feature();
                    $title        = $f->title;
                    $feature_path = self::create_path_from_name($title);
                    $header[5][]  = [$title, '/' . $feature_path, ''];
                }
            }

            $all_header[] = $header;
        }

        return $all_header;
    }

    final public function generate_sidebar()
    {
        $sidebar = $this->create_sidebar();
        $php     = <<<'PHP'
            <?php

            /**
             * --------------------------------------------------------------------
             * AUTO-GENERATED FILE
             * --------------------------------------------------------------------
             * This file was generated by `php spark omnia:sidebar`.
             * Do not edit this file manually.
             */
            return [
            PHP;
        foreach ($sidebar as $s) {
            [$title, $path, $icon, $prefix, $group_path, $menus] = $s;
            $php .= sprintf(
                "[%s, %s, %s, %s, %s, [\n",
                var_export($title, true),
                var_export($path, true),
                var_export($icon, true),
                var_export($prefix, true),
                var_export($group_path, true),
            );
            foreach ($menus as $menu) {
                [$nama, $link, $icon] = $menu;
                $php .= sprintf(
                    "\t[%s, %s, %s],\n",
                    var_export($nama, true),
                    var_export($link, true),
                    var_export($icon, true),
                );
            }
            $php .= "]],\n";
        }
        $php .= '];';

        return $php;
    }

    final public function get_icon_paths()
    {
        $paths = [];
        foreach ($this->routes as $route_class) {
            $route_instance = new $route_class();
            $paths[]        = $route_instance->get_icon_path();
        }
        return $paths;
    }
}
