<?php
declare(strict_types=1);

namespace App\Core\Route;

use App\Core\Controller\ControllerTemplate;

class RouteGroup
{
    /** @var list<class-string<RouteTemplate>> */
    private array $routes = [];

    public function __construct(array $routes){
        $this->routes = $routes;
    }

    private static function create_path_from_name(string $name): string
    {
        $value = preg_replace(
            '/([a-z])([A-Z])/',
            '$1-$2',
            $name
        );

        $value = preg_replace(
            '/([A-Z]+)([A-Z][a-z])/',
            '$1-$2',
            $value
        );
        $value = strtolower($value ?? '');
        $value = str_replace(' ', '-', $value);
        return $value;
    }

    /** @return array<string, list<class-string<ControllerTemplate>>> */
    private function get_controler_classes(): array {
        /** @var array<string, list<class-string<ControllerTemplate>>> */
        $all_routes = [];
        foreach($this->routes as $route){
            $r = new $route();
            $all_routes[$r->feature_group] = $r->features;
        }
        return $all_routes;
    }

    final public function create_routes(): array
    {
        $filter = ['filter' => 'checkpermission:1337,1,2,3,4001,4002,4003,4004'];

        $groups = [];

        foreach($this->get_controler_classes() as $group => $features) {
            $group_path = self::create_path_from_name($group);

            foreach ($features as $f => $show) {
                if($show !== 'HIDE'){
                    $f = $show;
                }
                $title = new $f()->title;
                $feature_path = self::create_path_from_name($title);;
                $path = "{$group_path}/{$feature_path}/";

                $route_group = [
                    'prefix'  => $path,
                    'options' => ['filter' => 'auth',],
                    'routes' => [],
                ];
                $paths = [
                    ['get',    'data',                  'index'],
                    ['get',    'audit',                 'audit'],
                    ['get',    'tambah',                'create_page'],
                    ['post',   'submittambah',          'create'],
                    ['get',    'edit/(:segment)',       'update_page/$1'],
                    ['post',   'submitedit/(:segment)', 'update/$1'],
                    ['delete', 'hapus/(:segment)',      'delete/$1'],
                    ['get',    'cetak/(:segment)',      'print/$1'],
                    ['get',    'modal/list',            'list'],
                    ['post',   'sampel/(:segment)',     'sampel/$1'],
                    ['post',   'bayar/(:segment)',      'bayar/$1'],
                    ['post',   'upload/(:num)',         'upload/$1'],
                    ['post',   'hapus-foto/(:num)',     'hapusFoto/$1'],
                    ['get',    '(:segment)',            'detail/$1']
                ];    

                foreach($paths as $p){
                    [$method, $uri, $action] = $p;
                    $route_group['routes'][] = [
                        'method'  => $method,
                        'uri'     => $uri,
                        'action'  => $action,
                        'class'   => $f,
                        'options' => $filter,
                    ];
                }
                $groups[] = $route_group;
            }
        }

        return $groups;
    }

    final public function generate_php(): string
    {
        $groups = $this->create_routes();
        $php = <<<'PHP'
    <?php

    /**
     * --------------------------------------------------------------------
     * AUTO-GENERATED FILE
     * --------------------------------------------------------------------
     * This file was generated by `php spark omnia:route`.
     * Do not edit this file manually.
     */

    use CodeIgniter\Router\RouteCollection;
    /**
     * @var RouteCollection $routes
     */

    PHP;
        
        foreach ($groups as $group) {
            $php .= sprintf(
                "\n\$routes->group(%s, ['filter' => '%s'], static function (RouteCollection \$routes) {\n",
                var_export($group['prefix'], true),
                $group['options']['filter'],
            );

            foreach ($group['routes'] as $route) {
                $php .= sprintf(
                    "    \$routes->%s(%s, [\\%s::class, %s], ['filter' => '%s']);\n",
                    $route['method'],
                    var_export($route['uri'], true),
                    $route['class'],
                    var_export($route['action'], true),
                    $route['options']['filter'],
                );
            }
            $php .= "});\n";
        }

        return $php;
    }

    private function get_icons(): array {
        /** @var array<string, string> */
        $all_icons = [];
        foreach($this->routes as $route){
            $r = new $route();
            $all_icons[$r->feature_group] = $r->icon;
        }
        return $all_icons;
    }
    final public function create_header()
    {
        $persetujuanrole   = [1337, 1, 2, 4001, 5001];
        $petugasrole       = [1337, 1, 2, 4001, 5001];
        $petugasdokterrole = [1337, 1, 2, 3, 4001, 5001];
        $dokterrole        = [1337, 1, 3, 4001, 5001];
        $loginadmin        = [1337, 1];
        $loginpetugas      = 2;
        $logindokter       = 3;

        $all_routes = $this->get_controler_classes();
        $all_icons  = $this->get_icons();
        $all_header = [];

        foreach ($all_routes as $group => $features) {
            $group_path = self::create_path_from_name($group);
            $icon = $all_icons[$group];

            if (count($features) === 1) {
                $title = new $features[0]()->title;
                $feature_path = self::create_path_from_name($title);
                $header = [$group, '/' . $group_path . '/' . $feature_path . '/data', $icon, '', $petugasrole, []];
            } else {
                $header = [$group, '', $icon, '/' . $group_path, $petugasrole];
                foreach ($features as $feature => $show) {
                    if($show !== 'HIDE'){
                        $feature = $show;
                    } else {
                        continue;
                    }

                    $f = new $feature();
                    $title = $f->title;
                    $feature_path = self::create_path_from_name($title);
                    $header[5][] = [$title, '/' . $feature_path, ''];
                }
            }
            
            $all_header[] = $header;
        }

        return $all_header;
    }
}