services:
  app:
    build:
      context: ..
      dockerfile: .config/Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - postgres

  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: