# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
php-version = "8.5.0"
threads     = 8
stack-size  = 8388608

[source]
workspace   = "."
paths       = ["app/Features", "app/Core",]
includes    = ["vendor", "app/Config", "app/Helpers"]
excludes    = ["app/Views/admin", "app/Views/user"]
extensions  = ["php"]

################################## FORMATTER ###################################
[formatter]
preset                                   = "default"
print-width                              = 120
tab-width                                = 4
use-tabs                                 = false
single-quote                             = true
trailing-comma                           = true
inline-empty-control-braces              = true
inline-empty-closure-braces              = true
inline-empty-function-braces             = true
inline-empty-method-braces               = true
empty-line-after-opening-tag             = false
align-assignment-like                    = true
null-type-hint                           = "null_pipe"
parentheses-around-new-in-member-access  = true

#################################### LINTER ####################################
[linter]
integrations = ["phpunit"]

[linter.rules]
ambiguous-function-call  = { enabled = false }
literal-named-argument   = { enabled = false }
halstead                 = { effort-threshold = 7000 }

################################### ANALYZER ###################################
[analyzer]
plugins                             = ["security", "performance", "type-safety"]
find-unused-definitions             = true
find-unused-expressions             = true
analyze-dead-code                   = true
memoize-properties                  = true
allow-possibly-undefined-array-keys = false
check-throws                        = true
check-missing-override              = true
find-unused-parameters              = true
strict-list-index-checks            = true
no-boolean-literal-comparison       = true
check-missing-type-hints            = true
register-super-globals              = true

################################### GUARD ######################################

[[guard.structural.rules]]
on = "app\\Features\\**\\**\\*Controller"
target = "class"
must-be-named = "*Controller"
must-be-final = true
# must-be-readonly = true
must-extend = "app\\Core\\Controller\\ControllerTemplate"
reason = "Controllers must be final and extend ControllerTemplate."

[[guard.structural.rules]]
on = "app\\Features\\**\\**\\*Model"
target = "class"
must-be-named = "*Model"
must-be-final = true
# must-be-readonly = true
must-extend = "app\\Core\\Model\\ModelTemplate"
reason = "Models must be final and extend ModelTemplate."

[[guard.structural.rules]]
on = "app\\Features\\**\\**\\*Database"
target = "class"
must-be-named = "*Database"
must-be-final = true
# must-be-readonly = true
must-extend = "app\\Core\\Database\\Template\\DatabaseTemplate"
reason = "Database must be final and extend DatabaseTemplate."

[[guard.structural.rules]]
on = "app\\Controllers\\**\\*"
target = "class"
must-be-final = true
must-extend = "app\\Core\\Controller\\Legacy\\ControllerTemplateLegacy"
reason = "Legacy controllers must be final and extend ControllerTemplateLegacy."